version: '3.8'

services:
  postgres:
    image: "postgres"
    container_name: "pluton-postgres"
    environment:
      TZ: "Europe/Berlin"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pluton
    ports:
      - "5432:5432"