### GET all revenues ###

GET http://localhost:6606/revenues

### GET revenue by ID ###

GET http://localhost:6606/revenues/aa7028dc-b596-4032-9f5b-22bb4ca019b4

### CREATE a new revenue ###

POST http://localhost:6606/revenues
Content-Type: application/json

{
  "name": "amazon",
  "comment": "Cost of each month for AWS",
  "amount": 500.00,
  "isIncome": false
}

### UPDATE revenue ###

PUT http://localhost:6606/revenues/aa7028dc-b596-4032-9f5b-22bb4ca019b4
Content-Type: application/json

{
  "name": "amazon",
  "comment": "Cost of each month for AWS (updated)",
  "amount": 100.00,
  "isIncome": false
}

### DELETE revenue ###

DELETE http://localhost:6606/revenues/aa7028dc-b596-4032-9f5b-22bb4ca019b4
