### GET all transactions ###

GET http://localhost:6606/transactions

### GET transaction by ID ###

GET http://localhost:6606/transactions/1

### CREATE a new transaction ###

POST http://localhost:6606/transactions
Content-Type: application/json

{
  "name": "John Doe",
  "comment": "johndoe@example.com",
  "amount": 123,
  "isIncome": true
}

### UPDATE transaction ###

PUT http://localhost:6606/transactions/1
Content-Type: application/json

{
  "name": "John Doe",
  "comment": "johndoe@example.com",
  "amount": 123,
  "isIncome": true
}

### DELETE transaction ###

DELETE http://localhost:6606/transactions/1
